services:
  image: "ghcr.io/eliasb-nu/coming-soon-v3:${GIT_COMMIT_HASH:-latest}"
  deploy:
    placement:
      constrains:
        - node.role == worker
    replicas: 2
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${DEPLOY_URL}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=cfACME"